version: '3'
services:
  app_carmix:
    image: 'app-carmix'
    build:
      context: .
    container_name: app_carmix-cont
    depends_on:
      - db_carmix
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_carmix:5432/postgres
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db_carmix:
    image: 'postgres:13.1-alpine'
    container_name: db_carmix
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=


